---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Running local action: ${{ github.repository }}"
        uses: ./
        with:
          tag: "v1.2.3"

      - name: "Running local action: ${{ github.repository }} [NOT SEMANTIC]"
        uses: ./
        with:
          tag: "v1.not-valid.3.garbage"

      - name: "Running local action: ${{ github.repository }} [OVERRIDE/ERROR]"
        uses: ./
        continue-on-error: true
        with:
          tag: "v1.not-valid.3.garbage"
          exit_on_fail: true
